version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - echo "No pre-build steps required"
    build:
      commands:
        - echo "No build steps required"
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
